---
title: "covid by 2016 Pres vote"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Devraj Kori"
date: "8/1/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(sf)
library(tidycensus)
library(scales)
library(gridExtra)
options(tigris_use_cache = TRUE)
```

```{r data_prep, include=FALSE}
# read in NYT covid data
US<-read_csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))%>%
  #filter out territories
  filter(!state%in%c("Puerto Rico","Virgin Islands","Guam","Northern Mariana Islands"))

acs18_vars<-load_variables(year=2017,dataset="acs5")
census_sf1_vars<-load_variables(year=2010,dataset="sf1")

#read in 2016 election results
election16<-read_csv(url("https://raw.githubusercontent.com/john-guerra/US_Elections_Results/master/2016_US_County_Level_Presidential_Results.csv"))%>%
  #make fips character
  mutate(GEOID= case_when(combined_fips<=9999~paste0("0",combined_fips),
                          TRUE~paste0(combined_fips)))%>%
  #since some states have multiple rows per county, aggregate up to County level
  group_by(GEOID,county_name,state_abbr)%>%
  summarise(votes_total = sum(total_votes),
            votes_dem = sum(votes_dem),
            votes_gop = sum(votes_gop))%>%
  ungroup()%>%
  #recalculate percentages
  mutate(per_dem = votes_dem/votes_total,
         per_gop = votes_gop/votes_total)

#merge rural_election with covid data
with_election<-US%>%
  inner_join(election16,by=c("fips" = "GEOID"))%>%
  mutate(trump_margin=per_gop-per_dem)


#create a function that returns percent rural for every county
retrieve_urban<-function(state){
  rural_split<-get_decennial(year=2010,
                             state=state,
                             variables=c("total"="P002001","urban"="P002003"),
                             geography="county")%>%
    #select("GEOID","variable","value")%>%
    #spread the data to make it wide
    spread(key="variable",value="value")
}

census_urban<-do.call(rbind,
                      lapply(unique(US$state),retrieve_urban))

with_urban<-US%>%
  inner_join(census_urban,by=c("fips" = "GEOID"))%>%
  filter(!is.na(urban))%>%
  mutate(pct_urban = urban/total)
```

```{r covid_pres_bar_charts_dark,echo=FALSE}
new_covid_num<-with_election%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="stack",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Net increase in\nCOVID cases",fill="County Trump\nvictory margin",
       x = NULL,
       title = "Daily increase in COVID cases by county 2016 pres vote (excludes NYC)")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    plot.background = element_rect(fill = "black",colour="white"),
    panel.background = element_rect(fill = "black", colour="white"),
    panel.grid = element_line(colour="dimgray"),
    legend.position="none",
    title = element_text(colour="white"))+
  scale_y_continuous(#label=comma
    )

new_covid_pct<-with_election%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="fill",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Share of COVID\ncase increase",fill="Trump victory\nmargin",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       #caption = "Sources: https://github.com/john-guerra/US_Elections_Results,https://github.com/nytimes/covid-19-data"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    plot.background = element_rect(fill = "black",colour="white"),
    panel.background = element_rect(fill = "black", colour="white"),
    panel.grid = element_line(colour="dimgray"),
    legend.position="bottom",
    legend.text = element_text(colour="white"),
    title = element_text(colour="white"))+
  scale_y_continuous(label=percent_format(suffix="% "))


grid.arrange(new_covid_num,new_covid_pct)
```

```{r covid_pres_bar_charts,echo=FALSE}
new_covid_num<-with_election%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="stack",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Net increase in\nCOVID cases",fill="County Trump\nvictory margin",
       x = NULL,
       title = "Daily increase in COVID cases by county 2016 pres vote (excludes NYC)")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="none",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(#label=comma
    )

new_covid_pct<-with_election%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="fill",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Share of COVID\ncase increase",fill="Trump victory\nmargin",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       #caption = "Sources: https://github.com/john-guerra/US_Elections_Results,https://github.com/nytimes/covid-19-data"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="bottom",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(label=percent_format(suffix="% "))


grid.arrange(new_covid_num,new_covid_pct)
```


```{r covid_deaths_pres,echo=FALSE}
options(scipen=999)
deaths_num<-with_election%>%
  #filter(state_abbr!="NY")%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_deaths = deaths - lag(deaths,default = 0))%>%
  ungroup()%>%
  filter(new_deaths>0)%>%
  group_by(date,trump_margin_binned)%>%
  summarise(deaths=sum(new_deaths))%>%
  ungroup()%>%
  arrange(desc(trump_margin_binned))%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=deaths,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="stack",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="COVID Deaths",fill="County Trump\nvictory margin",
       x = NULL,
       title = "Daily COVID Deaths by county 2016 pres vote (excludes NYC)")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="none",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(#label=comma
    )

deaths_pct<-with_election%>%

  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_deaths = deaths - lag(deaths,default = 0))%>%
  ungroup()%>%
  filter(new_deaths>0)%>%
  group_by(date,trump_margin_binned)%>%
  summarise(deaths=sum(new_deaths))%>%
  ungroup()%>%
  arrange(desc(trump_margin_binned))%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  #filter(deaths>=0)%>%
  ggplot(aes(x=date,y=deaths,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="fill",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Share of COVID deaths",fill="Trump victory\nmargin",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="bottom",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(label=percent_format(suffix="% "))+
  geom_hline(yintercept=.5)


grid.arrange(deaths_num,deaths_pct)
```


```{r covid_urban,echo=FALSE}
new_covid_urban<-with_urban%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  group_by(date,pct_urban)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=pct_urban))+
  geom_bar(stat="identity",position="stack",width=1)+
  #scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  scale_fill_viridis_c(direction=(-1))+
  labs(y="Net increase in\nCOVID cases",fill="County Urban\nPop. Share",
       x = NULL,
       title = "Daily increase in COVID cases by County Urban Population (excludes NYC)")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="none",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(#label=comma
    )

new_covid_pct_urban<-with_urban%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  group_by(date,pct_urban)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=pct_urban))+
  geom_bar(stat="identity",position="fill",width=1)+
  #scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  scale_fill_viridis_c(direction=(-1))+
  labs(y="Share of COVID\ncase increase",fill="County Urban\nPop. Share",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="grey"),
    legend.position="bottom",
    #title = element_text(colour="white")
    )+
  scale_y_continuous(label=percent_format(suffix="% "))


grid.arrange(new_covid_urban,new_covid_pct_urban)
```


```{r add_NYC, echo=FALSE, message=FALSE,warning=FALSE}
# add in NYC 
nyc_covid<-US%>%
  filter(county=="New York City")%>%
  mutate(fips="NYC")
# calculate Trump share in NYC counties
nyc_election<-election16%>%
  filter(state_abbr=="NY")%>%
  filter(county_name%in%c("New York County","Kings County","Bronx County","Richmond County", "Queens County"))%>%
  summarise(votes_total = sum(votes_total),
            votes_dem = sum(votes_dem),
            votes_gop = sum(votes_gop))%>%
  mutate(per_dem = votes_dem/votes_total,
         per_gop = votes_gop/votes_total,
         trump_margin=per_gop-per_dem,
         fips="NYC")

# comparison<-full_join(with_nyc%>%
#                         #filter(state_abbr!="NY")%>%
#                         group_by(fips)%>%
#                         arrange(date,.by_group = TRUE)%>%
#                         mutate(new_cases = cases - lag(cases,default = 0))%>%
#                         ungroup()%>%
#                         #remove recovered cases
#                         mutate(new_cases = case_when(new_cases<0 ~ 0,
#                                TRUE ~ new_cases))%>%
#                         group_by(date)%>%
#                         summarise(with_nyc_cases=sum(new_cases)),
#                       with_election%>%
#                         #filter(state_abbr!="NY")%>%
#                         group_by(fips)%>%
#                         arrange(date,.by_group = TRUE)%>%
#                         mutate(new_cases = cases - lag(cases,default = 0))%>%
#                         ungroup()%>%
#                         #remove recovered cases
#                         mutate(new_cases = case_when(new_cases<0 ~ 0,
#                                TRUE ~ new_cases))%>%
#                         group_by(date)%>%
#                         summarise(without_nyc_cases=sum(new_cases))
#     
# )
with_nyc<-nyc_covid%>%
  inner_join(nyc_election)%>%
  bind_rows(with_election)%>%
  arrange(fips)

with_nyc_covid_num<-with_nyc%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  arrange(desc(trump_margin_binned))%>%
  #mutate(trump_margin_binned = 0-trump_margin_binned)%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position=position_stack(reverse=TRUE),width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Net increase in\nCOVID cases",fill="County Trump\nvictory margin",
       x = NULL,
       title = "Daily increase in COVID cases by county 2016 pres vote")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="white"),
    #panel.grid = element_line(colour="dimgray"),
    legend.position="none"#,
    #title = element_text(colour="white")
    )+
  scale_y_continuous(#label=comma
    )

with_nyc_covid_pct<-with_nyc%>%
  #filter(state_abbr!="NY")%>%
  group_by(fips)%>%
  arrange(date,.by_group = TRUE)%>%
  mutate(new_cases = cases - lag(cases,default = 0))%>%
  ungroup()%>%
  #remove recovered cases
  mutate(new_cases = case_when(new_cases<0 ~ 0,
                               TRUE ~ new_cases))%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.2)~(-.2),
                                         trump_margin>(.2)~.2,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(new_cases=sum(new_cases))%>%
  ungroup()%>%
  arrange(desc(trump_margin_binned))%>%
  #mutate(trump_margin_binned = 0 -trump_margin_binned)%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=new_cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position=position_fill(reverse=TRUE),width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Share of COVID\ncase increase",fill="Trump victory\nmargin",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       #caption = "Sources: https://github.com/john-guerra/US_Elections_Results,https://github.com/nytimes/covid-19-data"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="white"),
    #panel.grid = element_line(colour="dimgray"),
    legend.position="bottom"#,
    #legend.text = element_text(colour="white"),
    #title = element_text(colour="white")
    )+
  scale_y_continuous(label=percent_format(suffix="% "))+
  geom_hline(yintercept=.5)


grid.arrange(with_nyc_covid_num,with_nyc_covid_pct)


```

Chart plotting all covid cases, not just new cases (no accounting for deaths/recoveries)

```{r total_covid_cases}
with_nyc_covid_total_num<-with_nyc%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.20)~(-.20),
                                         trump_margin>(.20)~.20,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(cases=sum(cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="stack",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="COVID Cases",fill="County Trump\nvictory margin",
       x = NULL,
       title = "County-level Daily COVID Cases by 2016 Presidential vote margin")+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="white"),
    #panel.grid = element_line(colour="dimgray"),
    legend.position="none"#,
    #title = element_text(colour="white")
    )+
  scale_y_continuous(#label=comma
    )

with_nyc_covid_total_pct<-with_nyc%>%
  mutate(trump_margin_binned = case_when(trump_margin<(-.20)~(-.20),
                                         trump_margin>(.20)~.20,
                                         TRUE~trump_margin))%>%
  group_by(date,trump_margin_binned)%>%
  summarise(cases=sum(cases))%>%
  ungroup()%>%
  filter(date>=as.Date("02-26-2020",format("%m-%d-%Y")))%>%
  ggplot(aes(x=date,y=cases,fill=trump_margin_binned))+
  geom_bar(stat="identity",position="fill",width=1)+
  scale_fill_gradient2(low="blue",mid="grey",high="red",label=percent)+
  labs(y="Share of COVID Cases",fill="Trump victory\nmargin",
       x=NULL#,
       #title = "Daily COVID case increases by 2016 Pres vote\n(excludes NYC)"
       #caption = "Sources: https://github.com/john-guerra/US_Elections_Results,https://github.com/nytimes/covid-19-data"
       )+
  guides(fill = guide_colourbar(barwidth = 15, barheight = 1))+
  theme_minimal()+
  theme(
    #plot.background = element_rect(fill = "black",colour="white"),
    #panel.background = element_rect(fill = "black", colour="white"),
    #panel.grid = element_line(colour="dimgray"),
    legend.position="bottom"#,
    #legend.text = element_text(colour="white"),
    #title = element_text(colour="white")
    )+
  scale_y_continuous(label=percent_format(suffix="%     "))


grid.arrange(with_nyc_covid_total_num,with_nyc_covid_total_pct)
```
